### PR TITLE
Update ava to the latest version

### PR DESCRIPTION
**Pull request by Janluke0**
This should solve #74 
maybe i merged too much tests, anyway they are very similar.
if needed the can be split later.

except for a error relative to the absence of array.flat() (maybe my node version? i dunno) 
it run correctly test and lint

i'am not sure about the coverage

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#74: Update ava to the latest version](https://issuehunt.io/repos/58227632/issues/74)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by emilos** [comment]
The issue mentioned renaming specs, not joining or splitting. Thanks for the effort!

**Comment by Janluke0** [comment]
i understand that but i think that the requirment "make names of the tests unique (based on what the test really does)" is not met if we:

-  add a number to differents test for the same usecase (if they do same things they should have the same name) (Ex https://github.com/buxlabs/pure-utilities/blob/master/test/spec/string.js#L59-L67)

- add a number to differents test for a different but similar usecase (if they do different things they should have different names)
(Ex https://github.com/buxlabs/pure-utilities/blob/master/test/spec/string.js#L19-L27)

 I thought to merge same usecase tests, remove duplicates and renamed unique usecase tests was the best solution to ensure code quality.

Please, if you can, let me know why you don't angree.

**Comment by emilos** [comment]
hey @Janluke0 

It's easier to find a failing spec if it has a different name and it's a separate spec than a one that has multiple asserts. I'm basically trying to save some time by posting the issues on IssueHunt so I'll just pick the first one that's close enough to the acceptance.

Thanks again!

**Comment by Janluke0** [comment]
If you angree with my arguments and time of pull requests is correct, it should be the mine.

but i actualy commented only to know if i did a bad job, at this point i think not so it's fine.

Thank you for your time and good luck with your project.

**Pull request closed without merging**
